FROM golang:1.23.3-alpine AS base
WORKDIR /home/app
RUN apk update \
    && apk add --no-cache protobuf \
    && apk add build-base \
    && rm -rf /var/cache/apk/* \
    && go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest \
    && export PATH="$PATH:$(go env GOPATH)/bin" \
    && go env -w CGO_ENABLED=1

COPY ./ .
RUN go mod tidy \
    && protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative api/api.proto \
    && cd server \
    && go build server.go \
    && cd ../client \
    && go build client.go

FROM alpine:3.20.3 AS final
WORKDIR /home
COPY --from=base /home/app/server/server .
COPY --from=base /home/app/client/client .
